image: "archlinux:latest"

before_script:
  - pacman -Syu --needed --noconfirm rust gcc

stages:
  - format
  - clippy
  - check

format:
  stage: format
  script:
    - cargo fmt --all -- --check

clippy:
  stage: clippy
  script:
    - cargo clippy --all -- -D warnings

check:
  stage: check
  script:
    - cargo check --all --verbose --release
