image: "archlinux:latest"

before_script:
  - pacman -Syu --needed --noconfirm rust gcc

stages:
  - lint
  - test

format:
  stage: lint
  script:
    - cargo fmt --all -- --check

clippy:
  stage: lint
  script:
    - cargo clippy --all -- -D warnings

test:
  stage: test
  script:
    - cargo test --all --release
