[package]
name = "genrebuild"
version = "0.1.0"
authors = ["Jelle van der Waa <jelle@archlinux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "0.9.0"
clap = "2.33.0"
anyhow = "1"
rayon = "1.3"

[profile.release]
opt-level = 3
lto = true
